apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: webapp
  namespace: openshift-gitops
spec:
  destination:
    namespace: dev
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: helm/webapp
    repoURL: "https://github.com/Marian199666/argocd-course-webapp-config.git"
    targetRevision: main
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true